// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfJDaXhrh3JleQcKOSqC-HA2Xar1fj6Ko',
    appId: '1:322746961568:web:b3e42ba2030fdc82d083c5',
    messagingSenderId: '322746961568',
    projectId: 'instagramclone-a91d0',
    authDomain: 'instagramclone-a91d0.firebaseapp.com',
    storageBucket: 'instagramclone-a91d0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqjUqUREmMFlZPpFErCz3j6PE-XObBGxY',
    appId: '1:322746961568:android:240c915a43cd0644d083c5',
    messagingSenderId: '322746961568',
    projectId: 'instagramclone-a91d0',
    storageBucket: 'instagramclone-a91d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-QiEdT0d97mcJnyb4hxbHCCL7ZDmYev8',
    appId: '1:322746961568:ios:2bfbad7af5700aafd083c5',
    messagingSenderId: '322746961568',
    projectId: 'instagramclone-a91d0',
    storageBucket: 'instagramclone-a91d0.appspot.com',
    iosBundleId: 'com.example.flutterInstagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-QiEdT0d97mcJnyb4hxbHCCL7ZDmYev8',
    appId: '1:322746961568:ios:2bfbad7af5700aafd083c5',
    messagingSenderId: '322746961568',
    projectId: 'instagramclone-a91d0',
    storageBucket: 'instagramclone-a91d0.appspot.com',
    iosBundleId: 'com.example.flutterInstagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfJDaXhrh3JleQcKOSqC-HA2Xar1fj6Ko',
    appId: '1:322746961568:web:bd69867d25202e7bd083c5',
    messagingSenderId: '322746961568',
    projectId: 'instagramclone-a91d0',
    authDomain: 'instagramclone-a91d0.firebaseapp.com',
    storageBucket: 'instagramclone-a91d0.appspot.com',
  );
}
